server:
  port: 8081

spring:
  application:
    name: fcfs-demo
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/loopers
    username: application
    password: application
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  config:
    import:
      - redis.yml
      - kafka.yml
  profiles:
    active: local,db-lock
